sm_study_uarsymfony:
    resource: "@SmStudyUarsymfonyBundle/Controller/"
    type:     annotation
    prefix:   /up-and-running-symphony2

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
